# Generated by Django 4.0 on 2022-01-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usermodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='order',
            field=models.CharField(choices=[('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='JR', max_length=2),
        ),
    ]
